---
template: 'mytemplate.tex'
documentclass: article
#classoption: sigconf
title: Standard Grammars for LTL and LDL
version: v0.1.0
#date: 2020-12-24
author:
- name: Marco Favorito
  affiliation: Sapienza University of Rome
  location: Department of Computer, Control and Management Engineering
  address: Via Ariosto, 25, 00185 Roma RM, Italy
  email: favorito@diag.uniroma1.it
  site: https://marcofavorito.me
bibliography: biblio.bib
abstract: The heterogeneity of tools that support temporal logic formulae 
  poses several challenges in terms of interoperability. This document 
  proposes standard grammars for Linear Temporal Logic (LTL) [@pnueli77] and 
  Linear Dynamic Logic [@vardi2011rise;@degiacomo2013].
link: https://arxiv.org/abs/2012.13638

include-before: |
  ```{=latex}
  ```
figPrefix:
  - "Fig."
  - "Figs."
secPrefix:
  - "Section"
  - "Sections"
...
